"""
Analyze CSV Test Reports.

This script demonstrates how to read and analyze CSV test reports
generated by the test automation framework.
"""

from framework.csv_logger import get_csv_logger
from pathlib import Path
import pandas as pd

def analyze_registrations():
    """Analyze user registration data."""
    print("\n" + "="*80)
    print("📊 USER REGISTRATION ANALYSIS")
    print("="*80)
    
    csv_logger = get_csv_logger()
    registrations = csv_logger.read_csv("user_registrations")
    
    if not registrations:
        print("⚠️ No registration data found")
        return
    
    # Convert to DataFrame for easier analysis
    df = pd.DataFrame(registrations)
    
    print(f"\n📈 Total Registrations: {len(df)}")
    print(f"✅ Successful: {len(df[df['Validation Result'] == 'Success'])}")
    print(f"❌ Failed: {len(df[df['Validation Result'] == 'Failed'])}")
    
    if len(df) > 0:
        print(f"\n📧 Recent Registrations:")
        print(df[['Timestamp', 'First Name', 'Last Name', 'Email', 'Validation Result']].tail(5).to_string(index=False))


def analyze_orders():
    """Analyze order data."""
    print("\n" + "="*80)
    print("📊 ORDER DETAILS ANALYSIS")
    print("="*80)
    
    csv_logger = get_csv_logger()
    orders = csv_logger.read_csv("order_details")
    
    if not orders:
        print("⚠️ No order data found")
        return
    
    df = pd.DataFrame(orders)
    
    print(f"\n📈 Total Orders: {len(df)}")
    print(f"✅ Successful: {len(df[df['Validation Result'] == 'Success'])}")
    print(f"❌ Failed: {len(df[df['Validation Result'] == 'Failed'])}")
    
    if len(df) > 0:
        print(f"\n🛒 Recent Orders:")
        print(df[['Timestamp', 'Order ID', 'Product Names', 'Total Amount', 'Validation Result']].tail(5).to_string(index=False))


def analyze_validations():
    """Analyze validation results."""
    print("\n" + "="*80)
    print("📊 VALIDATION RESULTS ANALYSIS")
    print("="*80)
    
    csv_logger = get_csv_logger()
    validations = csv_logger.read_csv("validation_results")
    
    if not validations:
        print("⚠️ No validation data found")
        return
    
    df = pd.DataFrame(validations)
    
    print(f"\n📈 Total Validations: {len(df)}")
    print(f"✅ Passed: {len(df[df['Result'] == 'Pass'])}")
    print(f"❌ Failed: {len(df[df['Result'] == 'Fail'])}")
    
    if len(df) > 0:
        print(f"\n🔍 Validation Summary by Type:")
        summary = df.groupby(['Validation Type', 'Result']).size().unstack(fill_value=0)
        print(summary)
        
        print(f"\n📋 Recent Validations:")
        print(df[['Timestamp', 'Test Name', 'Validation Type', 'Result']].tail(10).to_string(index=False))
        
        # Show failed validations
        failed = df[df['Result'] == 'Fail']
        if len(failed) > 0:
            print(f"\n❌ Failed Validations:")
            print(failed[['Timestamp', 'Test Name', 'Validation Type', 'Expected Value', 'Actual Value', 'Details']].to_string(index=False))


def analyze_cart_details():
    """Analyze shopping cart data."""
    print("\n" + "="*80)
    print("📊 SHOPPING CART ANALYSIS")
    print("="*80)
    
    csv_logger = get_csv_logger()
    carts = csv_logger.read_csv("cart_details")
    
    if not carts:
        print("⚠️ No cart data found")
        return
    
    df = pd.DataFrame(carts)
    
    print(f"\n📈 Total Cart Operations: {len(df)}")
    print(f"✅ Successful: {len(df[df['Validation Result'] == 'Success'])}")
    print(f"❌ Failed: {len(df[df['Validation Result'] == 'Failed'])}")
    
    if len(df) > 0:
        print(f"\n🛒 Recent Cart Operations:")
        print(df[['Timestamp', 'Product Names', 'Quantities', 'Total', 'Validation Result']].tail(5).to_string(index=False))


def generate_summary_report():
    """Generate overall summary report."""
    print("\n" + "="*80)
    print("📊 OVERALL TEST SUMMARY REPORT")
    print("="*80)
    
    csv_logger = get_csv_logger()
    
    # Count records in each CSV
    registrations = csv_logger.read_csv("user_registrations")
    orders = csv_logger.read_csv("order_details")
    validations = csv_logger.read_csv("validation_results")
    carts = csv_logger.read_csv("cart_details")
    
    print(f"\n📁 CSV Files Generated:")
    print(f"   - user_registrations.csv: {len(registrations)} records")
    print(f"   - order_details.csv: {len(orders)} records")
    print(f"   - validation_results.csv: {len(validations)} records")
    print(f"   - cart_details.csv: {len(carts)} records")
    
    # Calculate success rates
    if registrations:
        reg_df = pd.DataFrame(registrations)
        reg_success_rate = len(reg_df[reg_df['Validation Result'] == 'Success']) / len(reg_df) * 100
        print(f"\n✅ Registration Success Rate: {reg_success_rate:.1f}%")
    
    if validations:
        val_df = pd.DataFrame(validations)
        val_pass_rate = len(val_df[val_df['Result'] == 'Pass']) / len(val_df) * 100
        print(f"✅ Validation Pass Rate: {val_pass_rate:.1f}%")
    
    print(f"\n📂 CSV files location: reports/csv/")


if __name__ == "__main__":
    try:
        # Check if pandas is available
        import pandas as pd
        
        # Run all analyses
        generate_summary_report()
        analyze_registrations()
        analyze_orders()
        analyze_cart_details()
        analyze_validations()
        
        print("\n" + "="*80)
        print("✅ Analysis Complete!")
        print("="*80)
        
    except ImportError:
        print("⚠️ pandas not installed. Install with: pip install pandas")
        print("Showing basic analysis instead...\n")
        
        # Basic analysis without pandas
        csv_logger = get_csv_logger()
        
        registrations = csv_logger.read_csv("user_registrations")
        print(f"📊 Registrations: {len(registrations)} records")
        
        orders = csv_logger.read_csv("order_details")
        print(f"📊 Orders: {len(orders)} records")
        
        validations = csv_logger.read_csv("validation_results")
        print(f"📊 Validations: {len(validations)} records")
        
        carts = csv_logger.read_csv("cart_details")
        print(f"📊 Cart Operations: {len(carts)} records")
